version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-sms
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sms
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
